config/routes.rb
Rails.application.routes.draw do
  root 'splash#index'
  get 'splash/index'

  resources :payments
  resources :charges
  resources :invoices
  resources :addresses
  resources :phones
  resources :emails
  resources :people
  resources :memberships

  get 'reports/roster', controller: :reports, action: :roster
  get 'reports/balance_due', controller: :reports, action: :balance_due


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :person
  has_one :membership, through: :person
  include StartEndDates
  
  validates_presence_of :label
  validates_presence_of :number

  normalizes :number, with: -> { _1.format_phone_number }
  normalizes :label, with: -> { _1.strip.titleize }
  
  def number_str
    number.format_phone_number 
  end

  def phone_str
    [label, number_str].join(': ')
  end

end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  before_action :set_phone, only: %i[ show edit update destroy ]

  # GET /phones or /phones.json
  def index
    @phones = Phone.all
  end

  # GET /phones/1 or /phones/1.json
  def show
  end

  # GET /phones/new
  def new
    @person = Person.find(params[:person_id])
    @phone = @person.phones.build
  end

  # GET /phones/1/edit
  def edit
  end

  # POST /phones or /phones.json
  def create
    @person = Person.find(params[:person_id])
    @phone = @person.phones.build(phone_params)

    respond_to do |format|
      if @phone.save
        format.html { redirect_to membership_url(@phone.person.membership), notice: "Phone Number was successfully created." }
        format.json { render :show, status: :created, location: @phone }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phones/1 or /phones/1.json
  def update
    respond_to do |format|
      if @phone.update(phone_params)
        format.html { redirect_to membership_url(@phone.person.membership), notice: "Phone Number was successfully updated." }
        format.json { render :show, status: :ok, location: @phone }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phones/1 or /phones/1.json
  def destroy
    @membership = @phone.person.membership
    msg = @phone.set_end_date(params[:operation])

    respond_to do |format|
      format.html { redirect_to membership_url(@membership), notice: msg }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone
      @phone = Phone.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def phone_params
      params.require(:phone).permit(:start_date, :end_date, :label, :number)
    end
end

app/helpers/phones_helper.rb
module PhonesHelper
  
  def phone_str(phone)
    phone.current? ? phone.phone_str : content_tag(:del, phone.phone_str, class: 'fw-light fst-italic')
  end  

  def phone_link(phone)
    #link_to(phone_str(phone),edit_phone_path(phone), class:  'text-decoration-none')
    #safe_join([edit_link(nil, edit_phone_path(phone)), link_to(phone_str(phone),edit_phone_path(phone), class:  'text-decoration-none')], ' '.to_nb)
    safe_join([edit_link(nil, edit_phone_path(phone)), phone_str(phone)], ' '.to_nb)
  end

  def phone_links(person)
    person.phones.collect{|phone| phone_link(phone)}
  end

  def phones_links(person)
    safe_join(phone_links(person) << add_link(svg_phone_plus, new_phone_path(person_id: person)), '<br>'.html_safe)
  end

end

app/views/phones/_form.html.erb
<%= 
input_form(path) do |f|
  f << error_messages_for(:phone)
  f << input_table_form do |s|
    s << input_table_row('Label', required_text_field(:phone, :label))
    s << input_table_row('Number', required_text_field(:phone, :number))
    s << input_table_row('Start Date', std_text_field(:phone, :start_date, readonly: true)) 
    s << input_table_row('End Date', std_text_field(:phone, :end_date, readonly: true)) if phone.end_date.present?
    s << input_table_row('', submit_and_cancel_buttons('Save', 'Cancel', membership_path(phone.person.membership)))
    s << input_table_row('', loading_spinner)
  end
end
%>

<%= deactivate_reactivate_button_group(phone) %>

app/views/phones/_phone.html.erb
<div id="<%= dom_id phone %>">
  <p>
    <strong>Person:</strong>
    <%= phone.person_id %>
  </p>

  <p>
    <strong>Start date:</strong>
    <%= phone.start_date %>
  </p>

  <p>
    <strong>End date:</strong>
    <%= phone.end_date %>
  </p>

  <p>
    <strong>Label:</strong>
    <%= phone.label %>
  </p>

  <p>
    <strong>Number:</strong>
    <%= phone.number %>
  </p>

</div>

app/views/phones/edit.html.erb
<%= page_caption "Edit Phone Number for #{@phone.person.full_name}" %>

<%= render "form", phone: @phone, path: phone_path(@phone) %>

app/views/phones/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Phones</h1>

<div id="phones">
  <% @phones.each do |phone| %>
    <%= render phone %>
    <p>
      <%= link_to "Show this phone", phone %>
    </p>
  <% end %>
</div>

<%= link_to "New phone", new_phone_path %>

app/views/phones/new.html.erb
<%= page_caption "Add Phone Number for #{@phone.person&.full_name}" %>

<%= render "form", phone: @phone, path: phones_path(person_id: @phone.person_id) %>

app/views/phones/show.html.erb
<%= render @phone %>

<div>
  <%= back_to_member_button(@phone.person.membership) %>
</div>