config/routes.rb
Rails.application.routes.draw do
  root 'splash#index'
  get 'splash/index'

  resources :payments
  resources :charges
  resources :invoices
  resources :addresses
  resources :phones
  resources :emails
  resources :people
  resources :memberships

  get 'reports/roster', controller: :reports, action: :roster
  get 'reports/balance_due', controller: :reports, action: :balance_due


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :invoice, touch: true
  has_one :membership, through: :invoice
  validates_presence_of :date
  validates :amount, numericality: { greater_than: 0 }

  def payment_str
    "$" + [amount, check_number].join(' : ')
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: %i[ show edit update destroy ]

  # GET /payments or /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1 or /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
    @payment.invoice_id = params[:invoice_id]
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments or /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to invoices_path(membership_id: @payment.invoice.membership_id), notice: "Payment was successfully created." }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1 or /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to invoices_path(membership_id: @payment.invoice.membership_id), notice: "Payment was successfully updated." }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment.destroy!

    respond_to do |format|
      format.html { redirect_to invoices_path(membership_id: @payment.invoice.membership_id), notice: "Payment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def payment_params
      params.require(:payment).permit(:invoice_id, :date, :amount, :check_number)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
	def payment_str(payment)
		payment.payment_str
	end  

	def payment_link(payment)
		#link_to(payment_str(payment),edit_payment_path(payment), class:  'text-decoration-none')
		#safe_join([edit_link(nil, edit_payment_path(payment)), link_to(payment_str(payment),edit_payment_path(payment), class:  'text-decoration-none')], ' '.to_nb)
		safe_join([edit_link(nil, edit_payment_path(payment)), payment_str(payment)], ' '.to_nb)
	end

	def payment_links(invoice)
		invoice.payments.collect{|payment| payment_link(payment)}
	end

	def payments_links(invoice)
		safe_join(payment_links(invoice) << add_link(svg_plus, new_payment_path(invoice_id: invoice)), '<br>'.html_safe)
	end
end

app/views/payments/_form.html.erb
<%= 
input_form(path) do |f|
  f << error_messages_for(:payment)
  f << hidden_field(:payment, :invoice_id)
  f << input_table_form do |s|
    s << input_table_row('Date', required_date_field(:payment, :date))
    s << input_table_row('Check Number', required_text_field(:payment, :check_number))
    s << input_table_row('Amount', std_number_field(:payment, :amount))
    s << input_table_row('', submit_and_cancel_buttons('Save', 'Cancel', invoices_path(membership_id: payment.invoice.membership_id)))
    s << input_table_row('', loading_spinner)
  end
end
%>

<%= delete_button_cond(payment) %>

app/views/payments/_payment.html.erb
<div id="<%= dom_id payment %>">
  <p>
    <strong>Invoice:</strong>
    <%= payment.invoice_id %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= payment.date %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= payment.amount %>
  </p>

  <p>
    <strong>Check number:</strong>
    <%= payment.check_number %>
  </p>

</div>

app/views/payments/edit.html.erb
<%= page_caption "Edit Payment for #{@payment.invoice.membership&.last_names} Membership" %>

<%= render "form", payment: @payment, path: payment_path(@payment) %>

app/views/payments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Payments</h1>

<div id="payments">
  <% @payments.each do |payment| %>
    <%= render payment %>
    <p>
      <%= link_to "Show this payment", payment %>
    </p>
  <% end %>
</div>

<%= link_to "New payment", new_payment_path %>

app/views/payments/new.html.erb
<%= page_caption "Create payment for #{@payment.invoice.membership&.last_names} Membership" %>

<%= render "form", payment: @payment, path: payments_path(invoice_id: @invoice) %>

app/views/payments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @payment %>

<div>
  <%= link_to "Edit this payment", edit_payment_path(@payment) %> |
  <%= link_to "Back to payments", payments_path %>

  <%= button_to "Destroy this payment", @payment, method: :delete %>
</div>