config/routes.rb
Rails.application.routes.draw do
  root 'splash#index'
  get 'splash/index'

  resources :payments
  resources :charges
  resources :invoices
  resources :addresses
  resources :phones
  resources :emails
  resources :people
  resources :memberships

  get 'reports/roster', controller: :reports, action: :roster
  get 'reports/balance_due', controller: :reports, action: :balance_due


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/charge.rb
class Charge < ApplicationRecord
  belongs_to :invoice, touch: true
  has_one :membership, through: :invoice
  validates_presence_of :description
  validates :price, numericality: { greater_than_or_equal_to: 0 }

  def charge_str
    "$" + [price, description].join(' : ')
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :set_charge, only: %i[ show edit update destroy ]

  # GET /charges or /charges.json
  def index
    @charges = Charge.all
  end

  # GET /charges/1 or /charges/1.json
  def show
  end

  # GET /charges/new
  def new
    @charge = Charge.new
    @charge.invoice_id = params[:invoice_id]
  end

  # GET /charges/1/edit
  def edit
  end

  # POST /charges or /charges.json
  def create
    @charge = Charge.new(charge_params)

    respond_to do |format|
      if @charge.save
        format.html { redirect_to invoices_path(membership_id: @charge.invoice.membership_id), notice: "Charge was successfully created." }
        format.json { render :show, status: :created, location: @charge }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /charges/1 or /charges/1.json
  def update
    respond_to do |format|
      if @charge.update(charge_params)
        format.html { redirect_to invoices_path(membership_id: @charge.invoice.membership_id), notice: "Charge was successfully updated." }
        format.json { render :show, status: :ok, location: @charge }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charges/1 or /charges/1.json
  def destroy
    @charge.destroy!

    respond_to do |format|
      format.html { redirect_to invoices_path(membership_id: @charge.invoice.membership_id), notice: "Charge was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_charge
      @charge = Charge.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def charge_params
      params.require(:charge).permit(:invoice_id, :description, :price)
    end
end

app/helpers/charges_helper.rb
module ChargesHelper

	def charge_str(charge)
		charge.charge_str
	end  

	def charge_link(charge)
		#link_to(charge_str(charge),edit_charge_path(charge), class:  'text-decoration-none')
		#safe_join([edit_link(nil, edit_charge_path(charge)), link_to(charge_str(charge),edit_charge_path(charge), class:  'text-decoration-none')], ' '.to_nb)
		safe_join([edit_link(nil, edit_charge_path(charge)), charge_str(charge)], ' '.to_nb)
	end

	def charge_links(invoice)
		invoice.charges.collect{|charge| charge_link(charge)}
	end

	def charges_links(invoice)
		safe_join(charge_links(invoice) << add_link(svg_plus, new_charge_path(invoice_id: invoice)), '<br>'.html_safe)
	end

end

app/views/charges/_charge.html.erb
<div id="<%= dom_id charge %>">
  <p>
    <strong>Invoice:</strong>
    <%= charge.invoice_id %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= charge.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= charge.price %>
  </p>

</div>

app/views/charges/_form.html.erb
<%= 
input_form(path) do |f|
  f << error_messages_for(:charge)
  f << hidden_field(:charge, :invoice_id)
  f << input_table_form do |s|
    s << input_table_row('Description', required_text_field(:charge, :description))
    s << input_table_row('Price', std_number_field(:charge, :price))
    s << input_table_row('', submit_and_cancel_buttons('Save', 'Cancel', invoices_path(membership_id: charge.invoice.membership_id)))
    s << input_table_row('', loading_spinner)
  end
end
%>

<%= delete_button_cond(charge) %>

app/views/charges/edit.html.erb
<%= page_caption "Edit Charge for #{@charge.invoice.membership&.last_names} Membership" %>

<%= render "form", charge: @charge, path: charge_path(@charge) %>

app/views/charges/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Charges</h1>

<div id="charges">
  <% @charges.each do |charge| %>
    <%= render charge %>
    <p>
      <%= link_to "Show this charge", charge %>
    </p>
  <% end %>
</div>

<%= link_to "New charge", new_charge_path %>

app/views/charges/new.html.erb
<%= page_caption "Create Charge for #{@charge.invoice.membership&.last_names} Membership" %>

<%= render "form", charge: @charge, path: charges_path(invoice_id: @invoice) %>

app/views/charges/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @charge %>

<div>
  <%= link_to "Edit this charge", edit_charge_path(@charge) %> |
  <%= link_to "Back to charges", charges_path %>

  <%= button_to "Destroy this charge", @charge, method: :delete %>
</div>