config/routes.rb
Rails.application.routes.draw do
  root 'splash#index'
  get 'splash/index'

  resources :payments
  resources :charges
  resources :invoices
  resources :addresses
  resources :phones
  resources :emails
  resources :people
  resources :memberships

  get 'reports/roster', controller: :reports, action: :roster
  get 'reports/balance_due', controller: :reports, action: :balance_due


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/_banner_menu.erb
<div class=container>
<nav class="navbar navbar-expand-sm navbar-light bg-light">
  <a class="navbar-brand" href="<%= splash_index_path %>">
    <img src="/assets/osyc-arrowhead.png" width="25" height="25" alt="" loading="lazy">
    OSYC
  </a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" >
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active"><a class="nav-link" href="<%= memberships_path %>">Members</a></li>
      <li class="nav-item active"><a class="nav-link" href="<%= invoices_path %>">Invoices</a></li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown">Reports</a>
        <div class="dropdown-menu dropdown-menu-right" >
            <%= dropdown_item_link 'Roster', '/reports/roster', target: '_blank' %>
            <%= dropdown_item_link 'Balance Due', '/reports/balance_due', target: '_blank' %>
        </div>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"><%= svg_gear %></a>
        <div class="dropdown-menu dropdown-menu-right" >
            <%= dropdown_item_link 'My Account', null_path %>
            <%= dropdown_item_link 'Support', null_path %>
          <%= dropdown_divider %>
          <% if CurrentUser.logged_in? %>
            <%= dropdown_item_link 'Logout', null_path, class: "text-white bg-danger" %>
          <% elsif !is_login_page? %>
            <%= dropdown_item_link 'Login', null_path, class: "text-white bg-primary" %>
          <% end %>
        </div>
      </li>


    </ul>
  </div>
</nav>
</div>

app/views/layouts/_flash_messages.erb
<% # <!-- Adapted from https://human-se.github.io/rails-demos-n-deets-2020/demo-bootstrap-alerts/ --> %>

<% flash.each do |key, message| %>
  <% next unless message && [:error, :alert, :warn, :warning, :notice, :success].include?(key.to_sym) %>
  <div class=container>
	  <div class="alert <%= flash_class(key) %> alert-dismissible fade show" role="alert">
	  	<% if [:error, :alert, :warn, :warning].include?(key.to_sym) %> <h4 class="alert-heading"><%= key.capitalize %>:</h4> <% end %>
	    <strong><em><%= message %></em></strong>
	    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	  </div>
  </div>
<% end %>
<% flash.clear %>

app/views/layouts/_footer.erb
<!-- Copyright <%= Time.now.year %>, Riverside Consulting Group, LLC -->

app/views/layouts/_header.erb
<%= render partial: "layouts/banner_menu" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>OSYC</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">  
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body data-turbo-prefetch="false">
    <%= render partial: 'layouts/header' %>
    <div class=container>
      <%= render partial: 'layouts/flash_messages' %>
      <%= yield %>
    </div>
    <%= render partial: 'layouts/footer' %>
  </body>
</html>

app/views/layouts/reports.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>OSYC</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">  
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body data-turbo-prefetch="false">
    <div class=container>
      <%= yield %>
    </div>
  </body>
</html>